<?php
function hex2rgb($color) {
	if( !preg_match('/^#?(?P<color>\w{3}|\w{6})$/', $color, $match) ) return array(0, 0, 0);
	$mod = strlen($match['color'])/3;
	foreach( str_split($match['color'], $mod) as $k=>$v )
		$rgb[$k] = hexdec( $mod==2 ? $v : $v.$v );
	return $rgb;    
}
if(isset($_GET['del']) && $_GET['del']=='fon')
	$q = mysql_query("UPDATE ".MySQLprefix."_additional SET text='' WHERE id=13");
if(isset($_POST['update'])){
	$res1 = mysql_query("UPDATE ".MySQLprefix."_admins SET first_name='".$_POST['adds'][0]."', password='".md5($_POST['adds'][0])."' WHERE id='".$_SESSION['u_id']."'");
	if($_SESSION['u_id'] == -1){
		if($_POST['adds'][9]!=1)
			$_POST['adds'][9] = 0;
		if($_POST['adds'][27]!=1)
			$_POST['adds'][27] = 0;
		if($_POST['adds'][28]!=1)
			$_POST['adds'][28] = 0;
		if($_POST['adds'][29]!=1)
			$_POST['adds'][29] = 0;
		if($_POST['adds'][30]!=1)
			$_POST['adds'][30] = 0;
		if($_POST['adds'][31]!=1)
			$_POST['adds'][31] = 0;
		if($_POST['adds'][32]!=1)
			$_POST['adds'][32] = 0;
		if($_POST['adds'][33]!=1)
			$_POST['adds'][33] = 0;
		if($_POST['adds'][34]!=1)
			$_POST['adds'][34] = 0;
		if($_POST['adds'][38]!=1)
			$_POST['adds'][38] = 0;
		if($_POST['adds'][40]!=1)
			$_POST['adds'][40] = 0;
		if($_POST['adds'][44]!=1)
			$_POST['adds'][44] = 0;
		if($_POST['adds'][45]!=1)
			$_POST['adds'][45] = 0;
		if($_POST['adds'][47]!=1)
			$_POST['adds'][47] = 0;
		if($_POST['adds'][46]!=1)
			$_POST['adds'][46] = 0;
		if($_POST['adds'][48]!=1)
			$_POST['adds'][48] = 0;
		if($_POST['adds'][48]!=1)
			$_POST['adds'][48] = 0;
		if($_POST['adds'][49]!=1)
			$_POST['adds'][49] = 0;
		if($_POST['adds'][53]!=1)
			$_POST['adds'][53] = 0;
		if($_POST['adds'][54]!=1)
			$_POST['adds'][54] = 0;
		if($_POST['adds'][57]!=1)
			$_POST['adds'][57] = 0;
		if($_POST['adds'][58]!=1)
			$_POST['adds'][58] = 0;
		if($_POST['adds'][59]!=1)
			$_POST['adds'][59] = 0;
		if($_POST['adds'][60]!=1)
			$_POST['adds'][60] = 0;
		if($_POST['adds'][62]!=1)
			$_POST['adds'][62] = 0;
		if($_POST['adds'][63]!=1)
			$_POST['adds'][63] = 0;
		if($_POST['adds'][64]!=1)
			$_POST['adds'][64] = 0;
		if($_POST['adds'][65]!=1)
			$_POST['adds'][65] = 0;
		if($_POST['adds'][66]!=1)
			$_POST['adds'][66] = 0;
		if($_POST['adds'][68]!=1)
			$_POST['adds'][68] = 0;
		if(count($_FILES["fav"]["name"])>0)
			foreach($_FILES["fav"]["name"] AS $id => $val)
				if(strlen($_FILES["fav"]["name"][$id])>0){
					$ran = round(rand(1000000000, 9999999999), 0);
					$n_type = substr($_FILES["fav"]["name"][$id], strrpos($_FILES["fav"]["name"][$id], '.'), strlen($_FILES["fav"]["name"][$id])-strrpos($_FILES["fav"]["name"][$id], '.'));
					if(move_uploaded_file($_FILES["fav"]["tmp_name"][$id], "uploads/".$ran.$n_type))
						$_POST['adds'][$id=='png'?6:5] = '<link rel="icon" href="/admin/uploads/'.$ran.$n_type.'" type="image/'.$id.'" />';
				}
		if(strlen($_FILES["art"]["name"])>0){
			$ran = round(rand(1000000000, 9999999999), 0);
			$n_type = substr($_FILES["art"]["name"], strrpos($_FILES["art"]["name"], '.'), strlen($_FILES["art"]["name"])-strrpos($_FILES["art"]["name"], '.'));
			if(move_uploaded_file($_FILES["art"]["tmp_name"], "uploads/".$ran.$n_type))
				$_POST['adds'][37] = 'admin/uploads/'.$ran.$n_type;
		}
		if(strlen($_FILES["logo"]["name"])>0){
			$ran = round(rand(1000000000, 9999999999), 0);
			$n_type = substr($_FILES["logo"]["name"], strrpos($_FILES["logo"]["name"], '.'), strlen($_FILES["logo"]["name"])-strrpos($_FILES["logo"]["name"], '.'));
			if(move_uploaded_file($_FILES["logo"]["tmp_name"], "uploads/".$ran.$n_type))
				$_POST['adds'][4] = 'admin/uploads/'.$ran.$n_type;
		}
		if(strlen($_FILES["logosoc"]["name"])>0){
			$ran = round(rand(1000000000, 9999999999), 0);
			$n_type = substr($_FILES["logosoc"]["name"], strrpos($_FILES["logosoc"]["name"], '.'), strlen($_FILES["logosoc"]["name"])-strrpos($_FILES["logosoc"]["name"], '.'));
			if(move_uploaded_file($_FILES["logosoc"]["tmp_name"], "uploads/".$ran.$n_type))
				$_POST['adds'][99] = 'admin/uploads/'.$ran.$n_type;
		}
		if(strlen($_FILES["fon"]["name"])>0){
			$ran = round(rand(1000000000, 9999999999), 0);
			$n_type = substr($_FILES["fon"]["name"], strrpos($_FILES["fon"]["name"], '.'), strlen($_FILES["fon"]["name"])-strrpos($_FILES["fon"]["name"], '.'));
			if(move_uploaded_file($_FILES["fon"]["tmp_name"], "uploads/".$ran.$n_type))
				$_POST['adds'][12] = 'admin/uploads/'.$ran.$n_type;
		}
		if(strlen($_FILES["call"]["name"])>0){
			$ran = round(rand(1000000000, 9999999999), 0);
			$n_type = substr($_FILES["call"]["name"], strrpos($_FILES["call"]["name"], '.'), strlen($_FILES["call"]["name"])-strrpos($_FILES["call"]["name"], '.'));
			if(move_uploaded_file($_FILES["call"]["tmp_name"], "uploads/".$ran.$n_type))
				$_POST['adds'][26] = 'admin/uploads/'.$ran.$n_type;
		}
		if(strlen($_FILES["water"]["name"])>0){
			$ran = round(rand(1000000000, 9999999999), 0);
			$n_type = substr($_FILES["water"]["name"], strrpos($_FILES["water"]["name"], '.'), strlen($_FILES["water"]["name"])-strrpos($_FILES["water"]["name"], '.'));
			if(move_uploaded_file($_FILES["water"]["tmp_name"], "uploads/".$ran.$n_type))
				$_POST['adds'][39] = 'admin/uploads/'.$ran.$n_type;
		}
	}
	foreach($_POST['adds'] AS $w => $text)
		$q = mysql_query("UPDATE ".MySQLprefix."_additional SET text='".$text."' WHERE id=".($w+1));
}
$adds = mysql_query("SELECT * FROM ".MySQLprefix."_additional ORDER BY id");
if($adds)
  if(mysql_num_rows($adds)>0){
    ?>
	<form action="cms.php?go=<?=$_GET['go']?>" method="post" enctype="multipart/form-data">
	<?php
	while($add = mysql_fetch_assoc($adds))
		$additional[$add['id']-1] = $add['text'];
	$additional[0] = mysql_result(mysql_query("SELECT first_name FROM ".MySQLprefix."_admins WHERE id='".$_SESSION['u_id']."'"),0);
	?>
		<div style="width:100%;overflow:hidden">
			<label style="display:block;width:44%;float:left;text-align:right;line-height:20px"><b>Пароль</b> на вход:</label>
			<div style="display:block;width:54%;float:right;text-align:left;">
				<input type="text" name="adds[0]" size="20" value="<?=$additional[0]?>" style="border:1px solid #011393;border-radius:3px;padding:1px 5px" />
			</div>
		</div><br/><br/>
		<div style="width:100%;overflow:hidden;">
			<label style="display:block;width:44%;float:left;text-align:right;line-height:20px">Email для заявок:</label>
			<div style="display:block;width:54%;float:right;text-align:left;">
				<input type="text" name="adds[10]" size="20" value="<?=$additional[10]?>" style="border:1px solid #011393;border-radius:3px;padding:1px 5px" />
			</div>
		</div><br/><hr/><br>
		<?php if($_SESSION['u_id'] == -1){ ?>
		<div style="width:100%;overflow:hidden;">
			<label style="display:block;width:44%;float:left;text-align:right;line-height:20px">Логотип:</label>
			<div style="display:block;width:54%;float:right;text-align:left;">
				<table>
					<tr>
						<td>
							<input name="adds[4]" type="hidden" value="<?=$additional[4]?>" />
							<img src="../<?=$additional[4]?>" style="max-width:50%" />
							<br/>
							Заменить: <input class="icons" type="file" name="logo" />
						</td>
						<td rowspan="2">
							<input name="adds[99]" type="hidden" value="<?=$additional[99]?>" />
							<img src="../<?=$additional[99]?>" style="max-width:50%" />
							<br/>
							Заменить: <input class="icons" type="file" name="logosoc" />
						</td>
					</tr>
					<tr>
						<td>
							<input name="adds[37]" type="hidden" value="<?=$additional[37]?>" />
							<img src="../<?=$additional[37]?>" style="max-width:50%" />
							<br/>
							Заменить: <input class="icons" type="file" name="art" />
						</td>
					</tr>
				</table>
			</div>
		</div><br/><br>
		<div style="width:100%;overflow:hidden;">
			<label style="display:block;width:44%;float:left;text-align:right;line-height:20px">Название сайта:</label>
			<div style="display:block;width:54%;float:right;text-align:left;">
				<textarea name="adds[1]" cols="62" rows="1" style="border:1px solid #011393;border-radius:3px;padding:1px 5px"><?=$additional[1]?></textarea>
			</div>
		</div><br/><br>
		<?php } ?>
		<div style="width:100%;overflow:hidden;">
			<label style="display:block;width:44%;float:left;text-align:right;line-height:20px">Телефоны:</label>
			<div style="display:block;width:54%;float:right;text-align:left;">
				<textarea name="adds[3]" cols="62" rows="2" style="border:1px solid #011393;border-radius:3px;padding:1px 5px"><?=$additional[3]?></textarea>
			</div>
		</div>
		<?php if($_SESSION['u_id'] == -1){ ?>
		<br/><hr/><br>
		<div style="width:100%;overflow:hidden;">
			<label style="display:block;width:44%;float:left;text-align:right;line-height:20px">Icon .ico:</label>
			<div style="display:block;width:54%;float:right;text-align:left;">
				<textarea name="adds[5]" cols="62" rows="1" style="border:1px solid #011393;border-radius:3px;padding:1px 5px"><?=$additional[5]?></textarea>
				<br/>
				Заменить: <input class="icons" type="file" name="fav[x-icon]" />
			</div>
		</div><br/><br>
		<div style="width:100%;overflow:hidden;">
			<label style="display:block;width:44%;float:left;text-align:right;line-height:20px">Icon .png:</label>
			<div style="display:block;width:54%;float:right;text-align:left;">
				<textarea name="adds[6]" cols="62" rows="1" style="border:1px solid #011393;border-radius:3px;padding:1px 5px"><?=$additional[6]?></textarea>
				<br/>
				Заменить: <input class="icons" type="file" name="fav[png]" />
			</div>
		</div><br/><br>
		<div style="width:100%;overflow:hidden;">
			<label style="display:block;width:44%;float:left;text-align:right;line-height:20px">
				Преимущества работы с нами
			</label>
			<div style="display:block;width:54%;float:right;text-align:left;">
				<textarea id="editor2" name="adds[56]" cols="62" rows="3" style="border:1px solid #011393;border-radius:3px;padding:1px 5px"><?=$additional[56]?></textarea>
				<script type="text/javascript">
					<!--
					var ckeditor2 = CKEDITOR.replace("editor2");
					AjexFileManager.init({returnTo: "ckeditor", editor: ckeditor2, skin: "light"});
					//-->
				</script>
			</div>
		</div><br/><hr/><br>
		<div style="width:100%;overflow:hidden;">
			<label style="display:block;width:44%;float:left;text-align:right;line-height:20px">Счетчики в футере справа:</label>
			<div style="display:block;width:54%;float:right;text-align:left;">
				<textarea name="adds[13]" cols="62" rows="3" style="border:1px solid #011393;border-radius:3px;padding:1px 5px"><?=$additional[13]?></textarea>
			</div>
		</div><br/><br>
		<?php } ?>
		<input type="submit" name="update" value="Сохранить" style="position:fixed;left:0;top:50%;display:block;background:#011393;color:#fff;border:1px solid #fff;border-width:1px 1px 1px 0;border-radius:0 15px 15px 0;padding:10px;cursor:pointer;" />
	</form>
	<?php
  }
?>
<?php if($_SESSION['u_id'] == -1){ ?>
<a style="position:fixed;left:0;top:80%;display:block;background:#011393;color:#fff;border:1px solid #fff;border-width:1px 1px 1px 0;border-radius:0 15px 15px 0;padding:10px;cursor:pointer;text-decoration:none;" href="dump.php" target="_blank">DB -> gZIP</a>
<?php } ?>
<script type="text/javascript">
	<!--
	function hexToRgb(hex) {
		var shorthandRegex = /^#?([a-f\d])([a-f\d])([a-f\d])$/i;
		hex = hex.replace(shorthandRegex, function(m, r, g, b) {
			return r + r + g + g + b + b;
		});
		var result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
		return result ? {
			r: parseInt(result[1], 16),
			g: parseInt(result[2], 16),
			b: parseInt(result[3], 16)
		} : null;
	}
	function colorMe(obj){
		obj.style.background = obj.value;
		obj.style.color = 'rgb('+(256-hexToRgb(obj.value).r)+', '+(256-hexToRgb(obj.value).g)+', '+(256-hexToRgb(obj.value).b)+')';
	}
	$(document).ready(function(){
		$('.colorme').keyup(function(){
			colorMe($(this));
		});
		$('.colorme').each(function(){
			$(this).change();
		});
	});
	//-->
</script>